name: deploy practice

on:
  push:
    branches: [ "main" ]

jobs:
  server:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: secret key check
        run: echo ${{ secrets.THIS_IS_SECRET_NAME }}